name: Build

on:
  [push, pull_request]

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1.0.0

    - name: Cache node_modules
      uses: actions/cache@preview
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

    - name: Install
      run: |
        cd app && npm ci

    - name: Test
      run: |
        cd app && npm t

    - name: Audit
      run: |
        cd app && npm audit

    - name: Build
      run: |
        docker build -t animated-gif-service:$GITHUB_SHA .
